version: '2'
networks:
  default:
    driver: bridge
services:
  cipta-kerja-be:
    container_name: cipta-kerja-cm
    image: cipta-kerja-cm
    ports:
    - 3000:3000
    networks:
    - default
    stdin_open: true
    tty: true
